### ISSUE TITLE
Endelig utgave

### ISSUE THREAD

**Issue by bfg1981** [gamle-oslo-venstre/program#24]
Kunne vi endret, så det programmet som ligger ute ikke heter andre utkast, men fremstår som endelig versjon?

**Comment by nicomen** [comment]
Endret det som stod på forsiden av repoet. Er det andre steder det står andre utkast?

**Comment by bfg1981** [comment]
Ser ut som om det mangler en deployment til [gamle-oslo-venstre.github.io](https://gamle-oslo-venstre.github.io/program/)

**Comment by nicomen** [comment]
Aha, trykket på knappen.
